// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable
{
    public IWebDriver driver { get; private set; }
    public IDictionary<String, Object> vars { get; private set; }
    public IJavaScriptExecutor js { get; private set; }
    public SuiteTests()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<String, Object>();
    }
    public void Dispose()
    {
        driver.Quit();
    }
    [Fact]
    public void TesteRN03()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(1616, 868);
        driver.FindElement(By.Id("idDepartamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).SendKeys("a");
        driver.FindElement(By.Id("idDepartamento")).SendKeys("1");

        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("idDepartamento")).GetAttribute("value")));

        string ValorID = driver.FindElement(By.Id("idDepartamento")).GetAttribute("value");


        Assert.Equal("1", ValorID);


    }
    [Fact]
    public void TesteRN04()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(596, 832);
        driver.FindElement(By.Id("idDepartamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).SendKeys("10");
        driver.FindElement(By.Id("departamento")).Click();

        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("departamento")).GetAttribute("value")));

        string departamentoNome = driver.FindElement(By.Id("departamento")).GetAttribute("value");


        Assert.Equal("Sec. Educação", departamentoNome);
    }
    [Fact]
    public void TesteRN06()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(596, 832);
        driver.FindElement(By.Id("idFuncionario")).Click();
        driver.FindElement(By.Id("idFuncionario")).SendKeys("10");
        driver.FindElement(By.Id("departamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).SendKeys("10");

        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("departamento")).GetAttribute("value")));

        string departamentoNome = driver.FindElement(By.Id("departamento")).GetAttribute("value");


        var wait2 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait2.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("NomeFuncionario")).GetAttribute("value")));

        string funcionarioNome = driver.FindElement(By.Id("NomeFuncionario")).GetAttribute("value");


        var wait3 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait3.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("cargo")).GetAttribute("value")));

        string CargoNome = driver.FindElement(By.Id("cargo")).GetAttribute("value");


        Assert.Equal("Sec. Educação", departamentoNome);
        Assert.Equal("Reginaldo Santana", funcionarioNome);
        Assert.Equal("CIO", CargoNome);

    }
    [Fact]
    public void TesteRN07()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(596, 832);
        driver.FindElement(By.Id("idFuncionario")).Click();
        driver.FindElement(By.Id("idFuncionario")).SendKeys("10");
        driver.FindElement(By.Id("departamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).Click();
        driver.FindElement(By.Id("idDepartamento")).SendKeys("10");

        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("departamento")).GetAttribute("value")));

        string departamentoNome = driver.FindElement(By.Id("departamento")).GetAttribute("value");


        var wait2 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait2.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("NomeFuncionario")).GetAttribute("value")));

        string funcionarioNome = driver.FindElement(By.Id("NomeFuncionario")).GetAttribute("value");


        var wait3 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait3.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("cargo")).GetAttribute("value")));

        string CargoNome = driver.FindElement(By.Id("cargo")).GetAttribute("value");


        Assert.Equal("Sec. Educação", departamentoNome);
        Assert.Equal("Reginaldo Santana", funcionarioNome);
        Assert.Equal("CIO", CargoNome);

    }
    [Fact]
    public void TesteRN8()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(955, 832);
        driver.FindElement(By.Id("Estoque")).Click();
        driver.FindElement(By.Id("Estoque")).SendKeys("1111");

        var wait3 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait3.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("Estoque")).GetAttribute("value")));

        string estoque = driver.FindElement(By.Id("Estoque")).GetAttribute("value");


        Assert.NotEqual("1111", estoque);
    }

   
    [Fact]
    public void TesteRN9()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(1616, 868);
     
       
        driver.FindElement(By.Id("Estoque")).Click();
        driver.FindElement(By.Id("Estoque")).SendKeys("23123");
        var wait3 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait3.Until(driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("Estoque")).GetAttribute("value")));

        string estoque = driver.FindElement(By.Id("Estoque")).GetAttribute("value");


        Assert.NotEqual("23123", estoque);
    }
    [Fact]
    public void TesteRN10()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");
        driver.Manage().Window.Size = new System.Drawing.Size(1616, 868);
        driver.FindElement(By.Id("codigoProduto")).Click();
        driver.FindElement(By.Id("codigoProduto")).SendKeys("10");
        driver.FindElement(By.Id("Estoque")).Click();
        driver.FindElement(By.Id("Quantidade")).Click();
        driver.FindElement(By.Id("Quantidade")).SendKeys("-2");
       

        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(Driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("Estoque")).GetAttribute("value")));
        string estoque = driver.FindElement(By.Id("Estoque")).GetAttribute("value");

        Assert.NotEqual("-2", estoque);

    }
    [Fact]
    public void TesteRN11()
    {
        driver.Navigate().GoToUrl("https://guilhermeveigalopes.github.io/almoxarifado/");

        var wait2 = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait2.Until(Driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("verde")).GetAttribute("value")));
        string estoque1 = driver.FindElement(By.Id("verde")).GetAttribute("value");

        driver.FindElement(By.Id("codigoProduto")).Click();
        driver.FindElement(By.Id("codigoProduto")).SendKeys("10");
        driver.FindElement(By.Id("Estoque")).Click();
        driver.FindElement(By.Id("Estoque")).Click();
        driver.FindElement(By.Id("Estoque")).SendKeys("10");
        driver.FindElement(By.Id("Quantidade")).Click();
        driver.FindElement(By.Id("Quantidade")).SendKeys("1");



        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        wait.Until(Driver => !string.IsNullOrEmpty(driver.FindElement(By.Id("verde")).GetAttribute("value")));
        string estoque = driver.FindElement(By.Id("verde")).GetAttribute("value");

        Assert.NotEqual(estoque1, estoque); 
        driver.Close();

    }
    [Fact]
    public void TesteRN12()
    {
        // ... (código anterior)

        // Capture os atributos CSS antes de clicar nos elementos
        string urgenteBeforeClick = driver.FindElement(By.Id("urgente")).GetCssValue("attributeName");
        string medioBeforeClick = driver.FindElement(By.Id("medio")).GetCssValue("attributeName");
        string baixoBeforeClick = driver.FindElement(By.Id("baixo")).GetCssValue("attributeName");

        // Clique nos elementos
        driver.FindElement(By.Id("urgente")).Click();
        driver.FindElement(By.Id("medio")).Click();
        driver.FindElement(By.Id("baixo")).Click();

        // Capture os atributos CSS após clicar nos elementos
        string urgenteAfterClick = driver.FindElement(By.Id("urgente")).GetCssValue("attributeName");
        string medioAfterClick = driver.FindElement(By.Id("medio")).GetCssValue("attributeName");
        string baixoAfterClick = driver.FindElement(By.Id("baixo")).GetCssValue("attributeName");

        // Verifique se os atributos mudaram
        Assert.NotEqual(urgenteBeforeClick, urgenteAfterClick);
        Assert.NotEqual(medioBeforeClick, medioAfterClick);
        Assert.NotEqual(baixoBeforeClick, baixoAfterClick);
    }


}
